version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: patriciocostilla/challenge-2-app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - 8000:8000
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${DB_NAME}"]
      interval: 5s
      timeout: 60s
      retries: 12

volumes:
  db_data: