apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "challenge-2.fullname" . }}
  labels:
    {{- include "challenge-2.labels" . | nindent 4 }}
data:
  DJANGO_DEBUG: "{{ .Values.configmap.django_debug }}"
  ENVIRONMENT: "{{ .Values.configmap.environment }}"
  