apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "challenge-2.fullname" . }}
  labels:
    {{- include "challenge-2.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "challenge-2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "challenge-2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "challenge-2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "challenge-2.fullname" . }}
                  key: SECRET_KEY
                  optional: false
            - name: DB_ENGINE
              valueFrom:
                secretKeyRef:
                  name: {{ include "challenge-2.fullname" . }}
                  key: DB_ENGINE
                  optional: false
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "challenge-2.fullname" . }}
                  key: DB_NAME
                  optional: false
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "challenge-2.fullname" . }}
                  key: DB_USER
                  optional: false
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "challenge-2.fullname" . }}
                  key: DB_PASS
                  optional: false
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "challenge-2.fullname" . }}
                  key: DB_HOST
                  optional: false
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "challenge-2.fullname" . }}
                  key: DB_PORT
                  optional: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
