apiVersion: v1
kind: Secret
metadata:
  name: {{ include "challenge-2.fullname" . }}
  labels:
    {{- include "challenge-2.labels" . | nindent 4 }}
type: Opaque
data:
  DB_ENGINE: {{ .Values.secret.db_engine | b64enc }}
  DB_NAME: {{ .Values.postgresql.auth.database | b64enc }}
  DB_USER: {{ .Values.postgresql.auth.username | b64enc }}
  DB_PASS: {{ .Values.postgresql.auth.password | b64enc }}
  DB_HOST: {{ .Values.secret.db_host | b64enc }}
  DB_PORT: {{ .Values.secret.db_port | b64enc }}
stringData: 
  SECRET_KEY: {{ .Values.secret.secret_key }}
  