name: Build the 2nd challenge project and push it to Dockerhub
run-name: ${{ github.actor }}
on: 
  push:
    branches:
      - main
    paths:
      - challenge-2/**

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_USER }}/challenge-2-app:latest
          context: challenge-2



