name: Build the 3rd challenge project and push it to Dockerhub
run-name: ${{ github.actor }}
on: 
  push:
    branches:
      - main
    paths:
      - challenge-3/**

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_USER }}/challenge-3-app:latest
          context: challenge-3
  deploy:
    runs-on: ubuntu-22.04
    needs: [build-and-publish]
    steps:
      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA }}
      - uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          image: 'docker.io/${{ secrets.DOCKER_USER }}/challenge-3-app:latest'
          service: 'challenge-3-app'




